Popup modal window
prius2055/Portfolio-project pull request #13
Opened 2023-03-08 09:04 UTC by prius2055

### Pop-up modal window

**This is the pop-up modal window for the works section of the project**

- The works section is displayed when the page loads, using Javascript logic
- Clicking on any of the project cards brings up a modal that shows details of the project.

2023-03-08 14:01 UTC, Ibizugbe requested changes
Hi Team👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/223731954-9dd3eee9-bfcc-4202-80e6-ad8f99df291c.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Linters are passing👍
- [x] When the user clicks (or taps) the button to check project details, the popup with details about the project appears👍.
- [x] When the user clicks (or taps) the close (X) button, the popup disappears👍.
- [x] Github flow practice has been used👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- See comments below😎

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 15:09 UTC, prius2055 commented on index.html
> +            <!-- <div class="work-card">
Thank you. This has been fixed

2023-03-08 15:12 UTC, prius2055 commented on index.html
> +            <!-- <div class="work-card">
Thank you, I have fixed this

2023-03-10 13:08 UTC, Rustamxon7 approved these changes
Hi @prius2055, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯
3. Gerat readme documentation 💯 

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 14:29 UTC, merged